// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/azaliaz/subs-api/internal/application"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSubscriptionsService is a mock of SubscriptionsService interface.
type MockSubscriptionsService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsServiceMockRecorder
}

// MockSubscriptionsServiceMockRecorder is the mock recorder for MockSubscriptionsService.
type MockSubscriptionsServiceMockRecorder struct {
	mock *MockSubscriptionsService
}

// NewMockSubscriptionsService creates a new mock instance.
func NewMockSubscriptionsService(ctrl *gomock.Controller) *MockSubscriptionsService {
	mock := &MockSubscriptionsService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsService) EXPECT() *MockSubscriptionsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionsService) Create(ctx context.Context, request *application.CreateRequest) (*application.CreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(*application.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionsServiceMockRecorder) Create(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionsService)(nil).Create), ctx, request)
}

// Delete mocks base method.
func (m *MockSubscriptionsService) Delete(ctx context.Context, request *application.DeleteRequest) (*application.DeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, request)
	ret0, _ := ret[0].(*application.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionsServiceMockRecorder) Delete(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionsService)(nil).Delete), ctx, request)
}

// GetInfo mocks base method.
func (m *MockSubscriptionsService) GetInfo(ctx context.Context, request *application.GetInfoRequest) (*application.GetInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, request)
	ret0, _ := ret[0].(*application.GetInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockSubscriptionsServiceMockRecorder) GetInfo(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockSubscriptionsService)(nil).GetInfo), ctx, request)
}

// GetTotalSubscriptionsPrice mocks base method.
func (m *MockSubscriptionsService) GetTotalSubscriptionsPrice(ctx context.Context, request *application.TotalRequest) (*application.TotalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalSubscriptionsPrice", ctx, request)
	ret0, _ := ret[0].(*application.TotalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalSubscriptionsPrice indicates an expected call of GetTotalSubscriptionsPrice.
func (mr *MockSubscriptionsServiceMockRecorder) GetTotalSubscriptionsPrice(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalSubscriptionsPrice", reflect.TypeOf((*MockSubscriptionsService)(nil).GetTotalSubscriptionsPrice), ctx, request)
}

// List mocks base method.
func (m *MockSubscriptionsService) List(ctx context.Context, request *application.ListRequest) (*application.ListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, request)
	ret0, _ := ret[0].(*application.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubscriptionsServiceMockRecorder) List(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubscriptionsService)(nil).List), ctx, request)
}

// Update mocks base method.
func (m *MockSubscriptionsService) Update(ctx context.Context, id uuid.UUID, req *application.UpdateRequest) (*application.UpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*application.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionsServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionsService)(nil).Update), ctx, id, req)
}
